baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'PhD Workshop'
theme = 'hugo-theme-relearn'
[params]
  themeVariant = ['blue']
[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']