baseURL = 'https://diy-at.andreaspolydorides.com'
languageCode = 'en-us'
title = 'DIY-AT'
theme = 'hugo-theme-relearn'
[params]
  themeVariant = ['blue']
[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']
